blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/vbolshakov87/PhotoScout/discussions
    about: Ask questions or start a discussion about PhotoScout
